name: ESLint code check

on:
  push:
  pull_request:

jobs:
  eslint-check:
    timeout-minutes: 1
    name: Run ESLint checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: Install Dependecies
        run: npm install

      - name: Run ESLint checks
        run: BROWSERSTACK_USERNAME=${{ secrets.BROWSERSTACK_USERNAME }} BROWSERSTACK_ACCESS_KEY=${{ secrets.BROWSERSTACK_ACCESS_KEY }} npm run eslint:validate
